### PR TITLE
Test on PHP 7.4

### PR DESCRIPTION
**Pull request by driesvints**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
> The requested PHP extension ext-zip * is missing from your system. Install or enable PHP's zip extension.

Well, this is rubbish. Why travis removed it...

**Comment by driesvints** [comment]
@GrahamCampbell already reported this on the issue that was opened. Hopefull they'll re-add it soon: https://travis-ci.community/t/some-extensions-are-missing-in-php-7-4-0-zip-gmp-sodium/6320/13

**Comment by GrahamCampbell** [comment]
Heh. I just use docker for PHP builds on travis. :P

Example: https://github.com/GrahamCampbell/Laravel-Exceptions/blob/master/.travis.yml; https://travis-ci.org/GrahamCampbell/Laravel-Exceptions/builds/622315237.

**Comment by driesvints** [comment]
I'm gonna try out Github actions soon to see if it has any benefits for us.

**Comment by GrahamCampbell** [comment]
Simpler example: https://github.com/GrahamCampbell/Guzzle-Factory/blob/master/.travis.yml.

**Comment by GrahamCampbell** [comment]
> I'm gonna try out Github actions soon to see if it has any benefits for us.

I find that their build output is kinda clunky. Especially when there's lots of jobs, since they separate them all in the status.

**Pull request merged**
