### PR TITLE
Updated to use the Process constructor to install Pest 

### PR DESCRIPTION
**Pull request by rajabilal555**
For Issue #272
Pest failed to install in Windows PowerShell when selecting no Starter Kit on the initial prompt.

+ Added two new functions from the laravel\breeze repo
  - requireComposerPackages
  - removeComposerPackages
+ Updated the `installPest` function to use `requireComposerPackages` instead
+ Now we can use the `[require/remove]ComposerPackages` functions which handle escaping commands through the Process constructor.

### CODE REVIEW

**Comment by driesvints** [comment]
This lgtm but would like a second pair of eyes from @nunomaduro on this.

**Comment by taylorotwell** [comment]
@crynobone can we now refactor this to use your recent PR?

**Comment by nunomaduro** [comment]
@driesvints Waiting for @crynobone feedback first.

**Comment by taylorotwell** [comment]
Following up on @crynobone's PR.

**Pull request closed without merging**
