### PR TITLE
Fix composer.par path.

### PR DESCRIPTION
**Pull request by hikouki**

### CODE REVIEW

**Comment by vlakoff** [comment]
Maybe the path should be enclosed in double quotes?

**Comment by hikouki** [comment]
@vlakoff 

Thank you for replay :)

Fix it.

**Comment by GrahamCampbell** [comment]
Does this work on all operating systems?

**Comment by vlakoff** [comment]
Mmmm, at least on Windows, it seems to work as well without this added `getcwd()`.
Also, you shouldn't have removed the double quotes around PHP_BINARY.

Unless a failing example is provided, looks like the current code is just fine.

**Comment by hikouki** [comment]
Thank you for test 🍺 

Added the double quotes around PHP_BINARY.

**Comment by taylorotwell** [comment]
The current code seems fine unless someone has a serious bug with it.

**Comment by hikouki** [comment]
@taylorotwell 

Isn't this bug?

for MacOSX

**Pull request closed without merging**
