### PR TITLE
Allow TTY output from process

### PR DESCRIPTION
**Pull request by alexbowers**
This allows us to get the coloured output from Process.

### CODE REVIEW

**Comment by alexbowers** [comment]
Difference: 

Old:
image

New:

image

**Comment by alexbowers** [comment]
Dont really understand what is wrong with the style: https://styleci.io/analyses/XlKJxQ

**Comment by alexbowers** [comment]
Realised it was the spaces. Fixed the styling issues.

**Comment by taylorotwell** [comment]
Ha! I was wondering how to do that. <3

**Comment by alexbowers** [comment]
No problem.

**Comment by RobWJacob** [comment]
hi. i think this breaks laravel on windows. i installed laravel 1.3.1 days ago and worked on windows 10, now i updated to 1.3.2 and i can't add a new laravel project.

`laravel new blog`

i get an error
```
[Symfony\Component\Process\Exception\RuntimeException]  
  TTY mode is not supported on Windows platform.
```

i rolled back to installer 1.3.1 for now, this version works on windows ;)

**Comment by alexbowers** [comment]
Ah my bad,

I don't have a windows machine setup to test this, so if possible can you check whether it works if the following is added:

```php
if('\\' !== DIRECTORY_SEPARATOR && file_exists('/dev/tty') && is_readable('/dev/tty')) {
	$process->setTty(true);
}
```

This is based on what can cause it to throw an exception on Symfony's code.

https://github.com/symfony/process/blob/master/Process.php#L913

My apologies, I should have looked into the code more before implementing it.

**Comment by alexbowers** [comment]
https://github.com/laravel/installer/pull/48 Patch created for if that solution does work.

I'm signing off for the weekend now.

**Pull request merged**
