### PR TITLE
Add flag for selecting branch

### PR DESCRIPTION
**Pull request by rweas**
If you use the flag --b you can use whatever branch of laravel you like.

i.e. `laravel new mysite --b=develop`

See #13

### CODE REVIEW

**Comment by rweas** [comment]
@GrahamCampbell I thought that you were going to pull this in.

**Comment by GrahamCampbell** [comment]
Sorry, Taylor has to call it, not me.

**Comment by GrahamCampbell** [comment]
It's likely he will review this before the Laravel 5.0 launch.

**Comment by rweas** [comment]
@GrahamCampbell oh cool thanks for responding so quick.

**Comment by djallits** [comment]
@rweas It appears @taylorotwell didn't create a 4.X branch. So I am thinking the logic needs to be adjusted to use tagged releases.

**Comment by rweas** [comment]
@taylorotwell if I fix the problems @djallits mentioned will you reopen/merge or do you jist not like the idea of this PR?

**Pull request closed without merging**
