### PR TITLE
add telescope install support

### PR DESCRIPTION
**Pull request by umairparacha00**
This pull request adds support for the Laravel Telescope for both:
- Default installation
- Local only installation

### CODE REVIEW

**Comment by driesvints** [comment]
I don't think we should be adding all of the first party packages as flags to the installer like this.

**Comment by jessarcher** [comment]
I kinda like the idea of prompting for some first-party packages, but I reckon a multi-select would be better rather than confirmation prompts. It could even replace the starter-kit selection with a validation error to prevent selecting Jetstream _and_ Breeze. In addition to convenience, it would help bring awareness to available packages. On the other hand, it could make the installer overwhelming.

**Comment by umairparacha00** [comment]
To keep the installer minimal, we can just add the option to install telescope instead of confirmation prompt.

**Comment by umairparacha00** [comment]
Now, I have removed the confirmation prompt, and only when the user passes the option prompt will show up to about the installation type.

**Pull request closed without merging**
