### PR TITLE
Add --ver special version option 

### PR DESCRIPTION
**Pull request by sehirger**
Add special version argument

### CODE REVIEW

**Comment by Jubeki** [comment]
This is probably not recommended, due to file changes in the skeleton.

You can instead do the following:

```bash
composer create-project laravel/laravel:^10.0 example-app
```

**Comment by crynobone** [comment]
@Jubeki is correct. The installation commands is intended for Laravel 11 only.

**Comment by sehirger** [comment]
> This is probably not recommended, due to file changes in the skeleton.
> 
> You can instead do the following:
> 
> ```shell
> composer create-project laravel/laravel:^10.0 example-app
> ```

If you use composer to create a special version, you will encounter some difficulties in front-end configuration, such as TS support, brezz installation, etc.

**Comment by Jubeki** [comment]
The installer is a convenience for the latest stable Laravel Version (and the next upcoming major version).

You can always install an older Laravel version using composer and then manually install e.g. Breeze with `composer require laravel/breeze` and then `php artisan breeze:install` (though I don't know why you would want to create a Laravel 10 instead of Laravel 11 Application).
This should result in a similar experience.

Same with jestream:
```bash
composer require laravel/jetstream
php artisan jetstream:install
```

Afterwards only some database adjustments in the `.env`, migrate and you are also ready to go.

**Comment by sehirger** [comment]
> The installer is a convenience for the latest stable Laravel Version (and the next upcoming major version).
> 
> You can always install an older Laravel version using composer and then manually install e.g. Breeze with `composer require laravel/breeze` and then `php artisan breeze:install` (though I don't know why you would want to create a Laravel 10 instead of Laravel 11 Application). This should result in a similar experience.
> 
> Same with jestream:
> 
> ```shell
> composer require laravel/jetstream
> php artisan jetstream:install
> ```
> 
> Afterwards only some database adjustments in the `.env`, migrate and you are also ready to go.

I know the way you suggested to create the project, but from the perspective of convenience and speed, I think it is necessary to add the features of optional version. My above modification may be simple and crude, but I hope everyone can find a good way to add the features. Features that specify version to create Laravel projects.

**Comment by driesvints** [comment]
No plans for this as the installer is only intended to be used with the latest version of the framework.

**Pull request closed without merging**
